apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c8cfjpgig-go
  janus-idp.io/tekton: c8cfjpgig-go
  backstage.io/kubernetes-id: c8cfjpgig-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c8cfjpgig-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
